export const CHANNELS_SHOW_REQUEST = 'CHANNELS_SHOW_REQUEST';
export const CHANNELS_SHOW_FAILURE = 'CHANNELS_SHOW_FAILURE';
export const CHANNELS_SHOW_SUCCESS = 'CHANNELS_SHOW_SUCCESS';

export const CHANNELS_CREATE_REQUEST = 'CHANNELS_CREATE_REQUEST';
export const CHANNELS_CREATE_FAILURE = 'CHANNELS_CREATE_FAILURE';
export const CHANNELS_CREATE_SUCCESS = 'CHANNELS_CREATE_SUCCESS';

export const CHANNELS_REMOVE_REQUEST = 'CHANNELS_REMOVE_REQUEST';
export const CHANNELS_REMOVE_FAILURE = 'CHANNELS_REMOVE_FAILURE';
export const CHANNELS_REMOVE_SUCCESS = 'CHANNELS_REMOVE_SUCCESS';

export const CHANNELS_MODIFY_REQUEST = 'CHANNELS_MODIFY_REQUEST';
export const CHANNELS_MODIFY_FAILURE = 'CHANNELS_MODIFY_FAILURE';
export const CHANNELS_MODIFY_SUCCESS = 'CHANNELS_MODIFY_SUCCESS';